name: co_trade
description: A mobile application for CoTrade

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  fl_chart: ^0.12.0
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  provider: ^4.3.2+2
  fluttertoast: ^7.1.1
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
